creating deployment overlay for solver-f35-py310
thoth-station/solver pull request #5151
Opened 2022-03-15 18:09 UTC by Gregory-Pereira

## Related Issues and Dependencies

Addresses: https://github.com/thoth-station/s2i-thoth/issues/231
Related to: https://github.com/thoth-station/s2i-thoth/pull/235

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Create a new solver image from recently created base image https://quay.io/repository/thoth-station/s2i-thoth-f35-py310/.

2022-03-15 18:09 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sesheta** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @sesheta` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fsolver).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/solver/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["sesheta"]} -->

2022-03-15 18:10 UTC, Gregory-Pereira commented
/cc @fridex

2022-03-16 09:10 UTC, fridex reviewed
One question, otherwise lgtm 👍🏻 thanks!

2022-03-17 09:46 UTC, harshad16 commented on overlays/solver-fedora-35-py310/Pipfile.lock
> +{
verified the pipfile lock in my system, seems to be the same and has the same sha.
we are good with this.

2022-03-17 09:47 UTC, fridex commented on overlays/solver-fedora-35-py310/Pipfile.lock
> +{
Perfect, thanks 👍🏻

2022-03-17 09:47 UTC, fridex approved these changes
thanks @Gregory-Pereira 💯 👍🏻

2022-03-17 09:47 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/solver/pull/5151#pullrequestreview-912881997" title="Approved">fridex</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fsolver).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/solver/blob/master/OWNERS)~~ [fridex]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-03-17 09:47 UTC, harshad16 commented
/hold

2022-03-17 09:48 UTC, harshad16 requested changes
everything looks good to be merged
please include the solver in here too:

https://github.com/thoth-station/solver/blob/1d8ba2a01a276b5373fa0e4c6bae790aecbfeed9/.thoth.yaml#L6

2022-03-17 09:56 UTC, fridex commented
I've also verified running solver testsuite in the `quay.io/thoth-station/s2i-thoth-f35-py310:v0.32.3` base. It looks like solver works well for Fedora 35 running Python 3.10.

2022-03-17 10:02 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 4ecc7c6e64738f871d07f36bb54216cbc83f6904 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_solver/5151/pre-commit/1504397487052427264) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=solver&pr=5151). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/solver/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-18 09:35 UTC, harshad16 approved these changes
lgtm
thanks :100:

2022-03-18 09:35 UTC, harshad16 commented
/unhold

2022-03-18 09:36 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/solver/pull/5151#pullrequestreview-912881997" title="Approved">fridex</a>*, *<a href="https://github.com/thoth-station/solver/pull/5151#pullrequestreview-914131382" title="Approved">harshad16</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fsolver).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/solver/blob/master/OWNERS)~~ [fridex]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-03-18 09:37 UTC, merged